service: supervisor
app: fcms

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: eu-west-1
  environment: ${file(../../${self:provider.stage}-env.yml):environment}


plugins:
  - serverless-offline


functions:
  #Create one record in the DB
  create:
    handler: create.main
    events:
      - http:
          path: create
          method: post

  #Function to get a single record
  getOne:
    handler: getOne.main
    events:
      - http:
          path: getOne/{id}
          method: get

  #Function to get all the records from the DB
  getAll:
    handler: getAll.main
    events:
      - http:
          path: getAll
          method: get

  #Function to update a record in the DB
  update:
    handler: update.main
    events:
      - http:
          path: update/{id}
          method: put

  #Function to delete by Id
  delete:
    handler: delete.main
    events:
      - http:
          path: delete/{id}
          method: delete
